name: "auto-release"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-auto-release@v1
        with:
          prerelease: false
          publish: true
