name: PR Labels


on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: mauroalderete/action-assign-labels@v1
        with:
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
